### ISSUE TITLE
d3d10 problem

### ISSUE THREAD

**Issue by kokhatto** [lampuiho/Super-Robot-Wars-V-Premium-Music-Patch#1]
problem upon opening game after installing mod, vey likely an issue with the d3d10 file
the d3d10 file is also sized only 0 bytes for reasons i dont know
![d3d10](https://github.com/user-attachments/assets/66693f62-3de6-4b16-b6cc-91fb0c29e720)

**Comment by lampuiho** [comment]
Yea not sure why it had a corrupted file. I have reuploaded the correct file. Sorry for the trouble.

**Comment by kokhatto** [comment]
thats great! But unfortunately i got hit with a 0xc0000142 error after using the updated one and when i try using the other dll you provided i can open the game but the premium sound isnt present at all

**Comment by lampuiho** [comment]
Things to troubleshoot
1. Version of the game?
2. Did you patch the awb files correctly?

**Comment by kokhatto** [comment]
my game version is 2.0.150
i followed your instructions on patching the files by extracting everything to the game folder and opening the bat file, after the first try makes the game unopenable then i extracted the no avx dll overwriting the current dll file and the game can be opened but no premium sound

**Comment by lampuiho** [comment]
I think when I made it I made it on 2.0.148
I will see if my AOB has problems with 2.0.150 when I have time. Try reverting back to 2.0.148 and see if you see any problem?

**Comment by kokhatto** [comment]
got it, it may take a while for me too because im currently away from home because holidays and all so i hope i can get back ASAP

**Comment by kokhatto** [comment]
update: i rolled back to 2.0.148 and the game can be opened with premium sound mod working, no more 0xc0000142. So its currently not working on 2.0.150
My problem solved, ty for the help

**Comment by lampuiho** [comment]
Hi, I have had a brief look at the update. It isn't a problem with the code. They replaced the file that has the premium music song list. But you definitely have a problem with the avx version, I can run with the avx version without problem on the update. It just won't load the premium music.

EDIT: never mind. I made a mistake when testing the update. I actually have no problem with the update. The premium songs are displayed normally.
